### MODELAGEM DA INFERENCIA DE CAUSALIDADE DE ACIDENTES DE TRANSITO

 - Usando ordered logit para modelar primeiramente (sem a causa pois ela possui endogeinedade) o que influencia probabilisticamente em um acidente de transito.
 - Para o segundo modelo e feito com a endogeinedade para saber o impacto que as variaveis causam no acidente de transito sem se preocupar com o efeito probabilistico de o quanto digamos 1 km a mais influencia da probabilidade de ser um acidente de alta letalidade. Somente para direcionar politica publica (o onde agir)

In [1]:
import polars as pl
import pandas as pd
import statsmodels.api as sm
from patsy import dmatrix
import warnings

from statsmodels.tools.sm_exceptions import ConvergenceWarning
from statsmodels.miscmodels.ordinal_model import OrderedModel
from sklearn.preprocessing import StandardScaler
warnings.simplefilter('ignore', ConvergenceWarning)

import numpy as np

In [47]:
df = pl.read_parquet("./data/anuario_prf.parquet")
df = df.to_pandas()

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258737 entries, 0 to 258736
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   uf                      258737 non-null  category
 1   br                      258737 non-null  category
 2   km                      258737 non-null  int64
 3   causa_acidente          258737 non-null  category
 4   tipo_acidente           258737 non-null  category
 5   fase_dia                258737 non-null  category
 6   sentido_via             258737 non-null  category
 7   condicao_metereologica  258737 non-null  category
 8   tipo_pista              258737 non-null  category
 9   tracado_via             258737 non-null  category
 10  uso_solo                258737 non-null  category
 11  pessoas                 258737 non-null  int64
 12  veiculos                258737 non-null  int64
 13  latitude                258737 non-null  float64
 14  longitude               258737 non-null  float64
 15  risco                   258737 non-null  category
 16  data                    258737 non-null  datetime64[ms]
 17  mes                     258737 non-null  int8
 18  dia_semana_num          258737 non-null  int8
dtypes: category(11), datetime64[ms](1), float64(2), int64(3), int8(2)
memory usage: 15.1 MB

In [49]:
df['fase_dia'].unique()

['Pleno dia', 'Amanhecer', 'Anoitecer', 'Plena Noite']
Categories (4, object): ['Pleno dia', 'Amanhecer', 'Anoitecer', 'Plena Noite']

In [50]:
fase_dia_ordem = ['Pleno dia', 'Amanhecer', 'Anoitecer', 'Plena Noite']

df['fase_dia'] = pd.Categorical(
    df['fase_dia'], 
    categories=fase_dia_ordem, 
    ordered=False 
)


tracado_ordem = ['Reta', 'Curva', 'Aclive_Declive', 'Intersecao', 'Especial', 'Outro']

# Aplique a ordem
df['tracado_via'] = pd.Categorical(
    df['tracado_via'], 
    categories=tracado_ordem, 
    ordered=False
)

uf_ordem = ['RS', 'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
df['uf'] = pd.Categorical(
    df['uf'], 
    categories=uf_ordem, 
    ordered=False
)


clima_ordem = ['Céu Claro', 'Nublado', 'Chuva', 'Garoa/Chuvisco', 'Sol', 'Ignorado', 'Nevoeiro/Neblina', 'Vento', 'Granizo', 'Neve']
df['condicao_metereologica'] = pd.Categorical(
    df['condicao_metereologica'], 
    categories=clima_ordem, 
    ordered=False
)

In [51]:
colunas_para_escalar = ['km', 'pessoas', 'veiculos']

scaler = StandardScaler()

df[colunas_para_escalar] = scaler.fit_transform(df[colunas_para_escalar])

In [52]:
crash_counts = df['br'].value_counts()

state_counts = df.groupby('br')['uf'].nunique()

/tmp/ipykernel_37435/2834029756.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  state_counts = df.groupby('br')['uf'].nunique()

In [53]:
br_stats = pd.DataFrame({
    'total_acidentes': crash_counts,
    'num_estados': state_counts
})

In [54]:
min_estados = 5
top_brs_stats = br_stats[
    br_stats['num_estados'] >= min_estados
].sort_values(by='total_acidentes', ascending=False)

In [55]:
TOP_BRS_LIST = top_brs_stats.head(5).index.tolist()

In [56]:
print(f"As Top 5 BRs (>= {min_estados} estados e mais acidentes) são:")
print(TOP_BRS_LIST)
print("\nEstatísticas completas das BRs filtradas:")
print(top_brs_stats)

As Top 5 BRs (>= 5 estados e mais acidentes) são:
['101', '116', '153', '163', '364']

Estatísticas completas das BRs filtradas:
     total_acidentes  num_estados
br
101            44646           11
116            40240           10
153             9856            8
163             8910            5
364             7961            5
230             5794            7
316             4450            5
20              2741            5
158             2634            8
110             1197            5
235             1144            5
226              996            5
0                669           27

In [57]:
for br in TOP_BRS_LIST:
    df[f'br_{br}'] = (df['br'] == br).astype(int)
    
    df[f'km_br_{br}'] = df['km'] * df[f'br_{br}']

In [58]:
risco_order = pd.CategoricalDtype(
    categories=['baixo', 'medio', 'alto'],
    ordered=True
)
df['risco_ordenado'] = df['risco'].astype(risco_order)

In [59]:
y = df['risco_ordenado'].cat.codes

In [60]:
main_effects = [f"br_{br}" for br in TOP_BRS_LIST]
interaction_effects = [f"km_br_{br}" for br in TOP_BRS_LIST]
all_new_terms = main_effects + interaction_effects
new = " + ".join(all_new_terms)

In [61]:
formula_modelo_1 = f"""
    km + {new} + pessoas + veiculos + C(uf) +
    C(fase_dia) + C(condicao_metereologica) +
    C(tipo_pista) + C(tracado_via) + C(uso_solo) +
    C(sentido_via) + C(tipo_acidente) + C(mes) + C(dia_semana_num)
"""

In [62]:
formula_modelo_1

'\n    km + br_101 + br_116 + br_153 + br_163 + br_364 + km_br_101 + km_br_116 + km_br_153 + km_br_163 + km_br_364 + pessoas + veiculos + C(uf) +\n    C(fase_dia) + C(condicao_metereologica) +\n    C(tipo_pista) + C(tracado_via) + C(uso_solo) +\n    C(sentido_via) + C(tipo_acidente) + C(mes) + C(dia_semana_num)\n'

In [63]:
X1 = dmatrix(formula_modelo_1, df, return_type='dataframe')
X1.drop(columns=['Intercept'], inplace=True)

In [64]:
model = OrderedModel(y, X1, distr='logit')

In [65]:
iteration_counter = [0]
DEBUG_MODE = False

def show_optimized_progress(params):
    """
    Callback otimizado que mostra o progresso.
    
    - No modo normal (DEBUG_MODE=False), recalcula o LL e o Gradiente
      apenas a cada 10 iterações para ser RÁPIDO.
    - No modo debug (DEBUG_MODE=True), recalcula a cada 1 iteração.
    """
    iteration_counter[0] += 1
    
    print_frequency = 1 if DEBUG_MODE else 25
    
    if (iteration_counter[0] % print_frequency == 0):
        
        neg_ll = -model.loglike(params)
        gradient = model.score(params)
        grad_norm = np.linalg.norm(gradient) 
        
        print(f"Iter: {iteration_counter[0]:<3} | Neg. LL: {neg_ll:<15.4f} | Grad. Norm: {grad_norm:<12.6f}")

In [66]:
print("Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...")
print("="*60)
print(f"{'Iter':<3} | {'Neg. LL':<15} | {'Grad. Norm':<12}")
print("="*60)

fit_1 = model.fit(
    method='lbfgs', 
    callback=show_optimized_progress
)

print("="*60)
print("Ajuste concluído!")
print(fit_1.summary())

Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...
============================================================
Iter | Neg. LL         | Grad. Norm
============================================================
Iter: 25  | Neg. LL: 169313.9522     | Grad. Norm: 1487.019766
Iter: 50  | Neg. LL: 169130.4375     | Grad. Norm: 213.871415
Iter: 75  | Neg. LL: 169118.3505     | Grad. Norm: 56.832917
Iter: 100 | Neg. LL: 169116.2252     | Grad. Norm: 90.591351
Iter: 125 | Neg. LL: 169114.9861     | Grad. Norm: 28.847424
Iter: 150 | Neg. LL: 169112.8375     | Grad. Norm: 34.965657
Iter: 175 | Neg. LL: 169111.2723     | Grad. Norm: 36.446601
============================================================
Ajuste concluído!
                             OrderedModel Results
==============================================================================
Dep. Variable:                      y   Log-Likelihood:            -1.6911e+05
Model:                   OrderedModel   AIC:                         3.384e+05
Method:            Maximum Likelihood   BIC:                         3.394e+05
Date:                Sat, 15 Nov 2025
Time:                        21:48:25
No. Observations:              258737
Df Residuals:                  258641
Df Model:                          94
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
C(uf)[T.AC]                                            0.7059      0.085      8.283      0.000       0.539       0.873
C(uf)[T.AL]                                            0.7538      0.049     15.479      0.000       0.658       0.849
C(uf)[T.AP]                                            0.4897      0.093      5.251      0.000       0.307       0.673
C(uf)[T.AM]                                            0.6315      0.107      5.903      0.000       0.422       0.841
C(uf)[T.BA]                                            0.5302      0.028     18.797      0.000       0.475       0.585
C(uf)[T.CE]                                            0.7638      0.036     21.029      0.000       0.693       0.835
C(uf)[T.DF]                                            0.0416      0.050      0.828      0.408      -0.057       0.140
C(uf)[T.ES]                                            0.5616      0.033     16.988      0.000       0.497       0.626
C(uf)[T.GO]                                            0.4710      0.031     15.029      0.000       0.410       0.532
C(uf)[T.MA]                                            0.9294      0.037     24.972      0.000       0.856       1.002
C(uf)[T.MT]                                            0.4052      0.038     10.658      0.000       0.331       0.480
C(uf)[T.MS]                                            0.4898      0.038     12.728      0.000       0.414       0.565
C(uf)[T.MG]                                            0.4675      0.024     19.145      0.000       0.420       0.515
C(uf)[T.PA]                                            0.9203      0.041     22.505      0.000       0.840       1.000
C(uf)[T.PB]                                            0.7508      0.035     21.759      0.000       0.683       0.818
C(uf)[T.PR]                                            0.3170      0.025     12.722      0.000       0.268       0.366
C(uf)[T.PE]                                            0.7690      0.030     26.012      0.000       0.711       0.827
C(uf)[T.PI]                                            0.8916      0.036     25.024      0.000       0.822       0.961
C(uf)[T.RJ]                                            0.0230      0.028      0.831      0.406      -0.031       0.077
C(uf)[T.RN]                                            0.5818      0.037     15.545      0.000       0.508       0.655
C(uf)[T.RO]                                            0.2975      0.050      5.925      0.000       0.199       0.396
C(uf)[T.RR]                                            0.6381      0.091      6.997      0.000       0.459       0.817
C(uf)[T.SC]                                            0.2698      0.026     10.578      0.000       0.220       0.320
C(uf)[T.SP]                                            0.0819      0.030      2.688      0.007       0.022       0.142
C(uf)[T.SE]                                            0.6193      0.054     11.542      0.000       0.514       0.724
C(uf)[T.TO]                                            0.6390      0.055     11.597      0.000       0.531       0.747
C(fase_dia)[T.Amanhecer]                               0.2384      0.022     10.784      0.000       0.195       0.282
C(fase_dia)[T.Anoitecer]                               0.0990      0.021      4.657      0.000       0.057       0.141
C(fase_dia)[T.Plena Noite]                             0.2344      0.011     21.816      0.000       0.213       0.256
C(condicao_metereologica)[T.Nublado]                  -0.0519      0.014     -3.801      0.000      -0.079      -0.025
C(condicao_metereologica)[T.Chuva]                    -0.2612      0.017    -14.932      0.000      -0.296      -0.227
C(condicao_metereologica)[T.Garoa/Chuvisco]           -0.3166      0.028    -11.227      0.000      -0.372      -0.261
C(condicao_metereologica)[T.Sol]                       0.0245      0.022      1.141      0.254      -0.018       0.067
C(condicao_metereologica)[T.Ignorado]                  0.1474      0.038      3.837      0.000       0.072       0.223
C(condicao_metereologica)[T.Nevoeiro/Neblina]         -0.0100      0.050     -0.201      0.841      -0.108       0.088
C(condicao_metereologica)[T.Vento]                     0.0188      0.113      0.166      0.868      -0.203       0.240
C(condicao_metereologica)[T.Granizo]                  -0.4583      0.869     -0.527      0.598      -2.162       1.245
C(condicao_metereologica)[T.Neve]                     -0.3474      1.297     -0.268      0.789      -2.889       2.194
C(tipo_pista)[T.Simples]                               0.2222      0.012     19.046      0.000       0.199       0.245
C(tipo_pista)[T.Múltipla]                             -0.0050      0.019     -0.260      0.795      -0.042       0.032
C(tracado_via)[T.Curva]                                0.0089      0.013      0.672      0.502      -0.017       0.035
C(tracado_via)[T.Aclive_Declive]                      -0.0304      0.027     -1.117      0.264      -0.084       0.023
C(tracado_via)[T.Intersecao]                          -0.2903      0.027    -10.576      0.000      -0.344      -0.236
C(tracado_via)[T.Especial]                            -0.1019      0.052     -1.967      0.049      -0.203      -0.000
C(tracado_via)[T.Outro]                               -0.3555      0.032    -11.061      0.000      -0.418      -0.293
C(uso_solo)[T.Sim]                                    -0.1355      0.011    -12.675      0.000      -0.157      -0.115
C(sentido_via)[T.Crescente]                            0.0344      0.010      3.616      0.000       0.016       0.053
C(sentido_via)[T.Não Informado]                       -1.5575      0.163     -9.569      0.000      -1.877      -1.239
C(tipo_acidente)[T.Colisão traseira]                  -0.1158      0.021     -5.498      0.000      -0.157      -0.075
C(tipo_acidente)[T.Colisão frontal]                    1.1494      0.023     49.435      0.000       1.104       1.195
C(tipo_acidente)[T.Saída de leito carroçável]         -0.1547      0.021     -7.358      0.000      -0.196      -0.114
C(tipo_acidente)[T.Colisão com objeto]                -0.1220      0.025     -4.844      0.000      -0.171      -0.073
C(tipo_acidente)[T.Colisão lateral mesmo sentido]     -0.2871      0.024    -11.771      0.000      -0.335      -0.239
C(tipo_acidente)[T.Engavetamento]                     -1.5385      0.082    -18.779      0.000      -1.699      -1.378
C(tipo_acidente)[T.Colisão lateral sentido oposto]    -0.0211      0.033     -0.641      0.522      -0.086       0.043
C(tipo_acidente)[T.Colisão transversal]                0.3177      0.022     14.576      0.000       0.275       0.360
C(tipo_acidente)[T.Capotamento]                       -0.3026      0.039     -7.680      0.000      -0.380      -0.225
C(tipo_acidente)[T.Queda de ocupante de veículo]       0.0741      0.028      2.661      0.008       0.020       0.129
C(tipo_acidente)[T.Incêndio]                          -5.1718      0.296    -17.480      0.000      -5.752      -4.592
C(tipo_acidente)[T.Derramamento de carga]             -1.3586      0.185     -7.342      0.000      -1.721      -0.996
C(tipo_acidente)[T.Atropelamento de Pedestre]          1.2830      0.024     53.615      0.000       1.236       1.330
C(tipo_acidente)[T.Eventos atípicos]                  -0.0109      0.074     -0.148      0.883      -0.155       0.133
C(tipo_acidente)[T.Atropelamento de Animal]            0.0216      0.039      0.553      0.580      -0.055       0.098
C(tipo_acidente)[T.Sinistro pessoal de trânsito]       1.9944      0.481      4.147      0.000       1.052       2.937
C(mes)[T.2]                                           -0.0450      0.024     -1.897      0.058      -0.092       0.001
C(mes)[T.3]                                           -0.0476      0.023     -2.074      0.038      -0.093      -0.003
C(mes)[T.4]                                           -0.0228      0.023     -0.991      0.321      -0.068       0.022
C(mes)[T.5]                                           -0.0183      0.023     -0.805      0.421      -0.063       0.026
C(mes)[T.6]                                           -0.0477      0.023     -2.092      0.036      -0.092      -0.003
C(mes)[T.7]                                           -0.0550      0.023     -2.424      0.015      -0.099      -0.011
C(mes)[T.8]                                           -0.0291      0.023     -1.279      0.201      -0.074       0.015
C(mes)[T.9]                                           -0.0438      0.023     -1.919      0.055      -0.089       0.001
C(mes)[T.10]                                          -0.0192      0.024     -0.787      0.431      -0.067       0.029
C(mes)[T.11]                                          -0.0127      0.025     -0.512      0.609      -0.061       0.036
C(mes)[T.12]                                          -0.0452      0.024     -1.872      0.061      -0.092       0.002
C(dia_semana_num)[T.2]                                -0.0204      0.019     -1.089      0.276      -0.057       0.016
C(dia_semana_num)[T.3]                                -0.0290      0.019     -1.554      0.120      -0.065       0.008
C(dia_semana_num)[T.4]                                -0.0028      0.018     -0.152      0.879      -0.039       0.033
C(dia_semana_num)[T.5]                                 0.0235      0.018      1.334      0.182      -0.011       0.058
C(dia_semana_num)[T.6]                                 0.0607      0.017      3.514      0.000       0.027       0.095
C(dia_semana_num)[T.7]                                 0.0749      0.017      4.322      0.000       0.041       0.109
km                                                    -0.0294      0.007     -4.209      0.000      -0.043      -0.016
br_101                                                 0.0194      0.017      1.171      0.242      -0.013       0.052
br_116                                                -0.0602      0.016     -3.654      0.000      -0.093      -0.028
br_153                                                -0.0860      0.029     -2.947      0.003      -0.143      -0.029
br_163                                                -0.1962      0.036     -5.449      0.000      -0.267      -0.126
br_364                                                -0.0096      0.042     -0.231      0.817      -0.091       0.072
km_br_101                                              0.1214      0.017      7.112      0.000       0.088       0.155
km_br_116                                              0.0286      0.015      1.855      0.064      -0.002       0.059
km_br_153                                              0.0830      0.029      2.910      0.004       0.027       0.139
km_br_163                                              0.0332      0.021      1.599      0.110      -0.007       0.074
km_br_364                                              0.1990      0.027      7.372      0.000       0.146       0.252
pessoas                                               -0.2410      0.009    -25.715      0.000      -0.259      -0.223
veiculos                                              -0.0350      0.007     -4.816      0.000      -0.049      -0.021
0/1                                                    1.7475      0.035     50.275      0.000       1.679       1.816
1/2                                                    0.4111      0.005     88.461      0.000       0.402       0.420
======================================================================================================================

In [67]:
print(fit_1.summary())
fit_1.save("./results/inference1.pkl")

                             OrderedModel Results
==============================================================================
Dep. Variable:                      y   Log-Likelihood:            -1.6911e+05
Model:                   OrderedModel   AIC:                         3.384e+05
Method:            Maximum Likelihood   BIC:                         3.394e+05
Date:                Sat, 15 Nov 2025
Time:                        21:48:25
No. Observations:              258737
Df Residuals:                  258641
Df Model:                          94
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
C(uf)[T.AC]                                            0.7059      0.085      8.283      0.000       0.539       0.873
C(uf)[T.AL]                                            0.7538      0.049     15.479      0.000       0.658       0.849
C(uf)[T.AP]                                            0.4897      0.093      5.251      0.000       0.307       0.673
C(uf)[T.AM]                                            0.6315      0.107      5.903      0.000       0.422       0.841
C(uf)[T.BA]                                            0.5302      0.028     18.797      0.000       0.475       0.585
C(uf)[T.CE]                                            0.7638      0.036     21.029      0.000       0.693       0.835
C(uf)[T.DF]                                            0.0416      0.050      0.828      0.408      -0.057       0.140
C(uf)[T.ES]                                            0.5616      0.033     16.988      0.000       0.497       0.626
C(uf)[T.GO]                                            0.4710      0.031     15.029      0.000       0.410       0.532
C(uf)[T.MA]                                            0.9294      0.037     24.972      0.000       0.856       1.002
C(uf)[T.MT]                                            0.4052      0.038     10.658      0.000       0.331       0.480
C(uf)[T.MS]                                            0.4898      0.038     12.728      0.000       0.414       0.565
C(uf)[T.MG]                                            0.4675      0.024     19.145      0.000       0.420       0.515
C(uf)[T.PA]                                            0.9203      0.041     22.505      0.000       0.840       1.000
C(uf)[T.PB]                                            0.7508      0.035     21.759      0.000       0.683       0.818
C(uf)[T.PR]                                            0.3170      0.025     12.722      0.000       0.268       0.366
C(uf)[T.PE]                                            0.7690      0.030     26.012      0.000       0.711       0.827
C(uf)[T.PI]                                            0.8916      0.036     25.024      0.000       0.822       0.961
C(uf)[T.RJ]                                            0.0230      0.028      0.831      0.406      -0.031       0.077
C(uf)[T.RN]                                            0.5818      0.037     15.545      0.000       0.508       0.655
C(uf)[T.RO]                                            0.2975      0.050      5.925      0.000       0.199       0.396
C(uf)[T.RR]                                            0.6381      0.091      6.997      0.000       0.459       0.817
C(uf)[T.SC]                                            0.2698      0.026     10.578      0.000       0.220       0.320
C(uf)[T.SP]                                            0.0819      0.030      2.688      0.007       0.022       0.142
C(uf)[T.SE]                                            0.6193      0.054     11.542      0.000       0.514       0.724
C(uf)[T.TO]                                            0.6390      0.055     11.597      0.000       0.531       0.747
C(fase_dia)[T.Amanhecer]                               0.2384      0.022     10.784      0.000       0.195       0.282
C(fase_dia)[T.Anoitecer]                               0.0990      0.021      4.657      0.000       0.057       0.141
C(fase_dia)[T.Plena Noite]                             0.2344      0.011     21.816      0.000       0.213       0.256
C(condicao_metereologica)[T.Nublado]                  -0.0519      0.014     -3.801      0.000      -0.079      -0.025
C(condicao_metereologica)[T.Chuva]                    -0.2612      0.017    -14.932      0.000      -0.296      -0.227
C(condicao_metereologica)[T.Garoa/Chuvisco]           -0.3166      0.028    -11.227      0.000      -0.372      -0.261
C(condicao_metereologica)[T.Sol]                       0.0245      0.022      1.141      0.254      -0.018       0.067
C(condicao_metereologica)[T.Ignorado]                  0.1474      0.038      3.837      0.000       0.072       0.223
C(condicao_metereologica)[T.Nevoeiro/Neblina]         -0.0100      0.050     -0.201      0.841      -0.108       0.088
C(condicao_metereologica)[T.Vento]                     0.0188      0.113      0.166      0.868      -0.203       0.240
C(condicao_metereologica)[T.Granizo]                  -0.4583      0.869     -0.527      0.598      -2.162       1.245
C(condicao_metereologica)[T.Neve]                     -0.3474      1.297     -0.268      0.789      -2.889       2.194
C(tipo_pista)[T.Simples]                               0.2222      0.012     19.046      0.000       0.199       0.245
C(tipo_pista)[T.Múltipla]                             -0.0050      0.019     -0.260      0.795      -0.042       0.032
C(tracado_via)[T.Curva]                                0.0089      0.013      0.672      0.502      -0.017       0.035
C(tracado_via)[T.Aclive_Declive]                      -0.0304      0.027     -1.117      0.264      -0.084       0.023
C(tracado_via)[T.Intersecao]                          -0.2903      0.027    -10.576      0.000      -0.344      -0.236
C(tracado_via)[T.Especial]                            -0.1019      0.052     -1.967      0.049      -0.203      -0.000
C(tracado_via)[T.Outro]                               -0.3555      0.032    -11.061      0.000      -0.418      -0.293
C(uso_solo)[T.Sim]                                    -0.1355      0.011    -12.675      0.000      -0.157      -0.115
C(sentido_via)[T.Crescente]                            0.0344      0.010      3.616      0.000       0.016       0.053
C(sentido_via)[T.Não Informado]                       -1.5575      0.163     -9.569      0.000      -1.877      -1.239
C(tipo_acidente)[T.Colisão traseira]                  -0.1158      0.021     -5.498      0.000      -0.157      -0.075
C(tipo_acidente)[T.Colisão frontal]                    1.1494      0.023     49.435      0.000       1.104       1.195
C(tipo_acidente)[T.Saída de leito carroçável]         -0.1547      0.021     -7.358      0.000      -0.196      -0.114
C(tipo_acidente)[T.Colisão com objeto]                -0.1220      0.025     -4.844      0.000      -0.171      -0.073
C(tipo_acidente)[T.Colisão lateral mesmo sentido]     -0.2871      0.024    -11.771      0.000      -0.335      -0.239
C(tipo_acidente)[T.Engavetamento]                     -1.5385      0.082    -18.779      0.000      -1.699      -1.378
C(tipo_acidente)[T.Colisão lateral sentido oposto]    -0.0211      0.033     -0.641      0.522      -0.086       0.043
C(tipo_acidente)[T.Colisão transversal]                0.3177      0.022     14.576      0.000       0.275       0.360
C(tipo_acidente)[T.Capotamento]                       -0.3026      0.039     -7.680      0.000      -0.380      -0.225
C(tipo_acidente)[T.Queda de ocupante de veículo]       0.0741      0.028      2.661      0.008       0.020       0.129
C(tipo_acidente)[T.Incêndio]                          -5.1718      0.296    -17.480      0.000      -5.752      -4.592
C(tipo_acidente)[T.Derramamento de carga]             -1.3586      0.185     -7.342      0.000      -1.721      -0.996
C(tipo_acidente)[T.Atropelamento de Pedestre]          1.2830      0.024     53.615      0.000       1.236       1.330
C(tipo_acidente)[T.Eventos atípicos]                  -0.0109      0.074     -0.148      0.883      -0.155       0.133
C(tipo_acidente)[T.Atropelamento de Animal]            0.0216      0.039      0.553      0.580      -0.055       0.098
C(tipo_acidente)[T.Sinistro pessoal de trânsito]       1.9944      0.481      4.147      0.000       1.052       2.937
C(mes)[T.2]                                           -0.0450      0.024     -1.897      0.058      -0.092       0.001
C(mes)[T.3]                                           -0.0476      0.023     -2.074      0.038      -0.093      -0.003
C(mes)[T.4]                                           -0.0228      0.023     -0.991      0.321      -0.068       0.022
C(mes)[T.5]                                           -0.0183      0.023     -0.805      0.421      -0.063       0.026
C(mes)[T.6]                                           -0.0477      0.023     -2.092      0.036      -0.092      -0.003
C(mes)[T.7]                                           -0.0550      0.023     -2.424      0.015      -0.099      -0.011
C(mes)[T.8]                                           -0.0291      0.023     -1.279      0.201      -0.074       0.015
C(mes)[T.9]                                           -0.0438      0.023     -1.919      0.055      -0.089       0.001
C(mes)[T.10]                                          -0.0192      0.024     -0.787      0.431      -0.067       0.029
C(mes)[T.11]                                          -0.0127      0.025     -0.512      0.609      -0.061       0.036
C(mes)[T.12]                                          -0.0452      0.024     -1.872      0.061      -0.092       0.002
C(dia_semana_num)[T.2]                                -0.0204      0.019     -1.089      0.276      -0.057       0.016
C(dia_semana_num)[T.3]                                -0.0290      0.019     -1.554      0.120      -0.065       0.008
C(dia_semana_num)[T.4]                                -0.0028      0.018     -0.152      0.879      -0.039       0.033
C(dia_semana_num)[T.5]                                 0.0235      0.018      1.334      0.182      -0.011       0.058
C(dia_semana_num)[T.6]                                 0.0607      0.017      3.514      0.000       0.027       0.095
C(dia_semana_num)[T.7]                                 0.0749      0.017      4.322      0.000       0.041       0.109
km                                                    -0.0294      0.007     -4.209      0.000      -0.043      -0.016
br_101                                                 0.0194      0.017      1.171      0.242      -0.013       0.052
br_116                                                -0.0602      0.016     -3.654      0.000      -0.093      -0.028
br_153                                                -0.0860      0.029     -2.947      0.003      -0.143      -0.029
br_163                                                -0.1962      0.036     -5.449      0.000      -0.267      -0.126
br_364                                                -0.0096      0.042     -0.231      0.817      -0.091       0.072
km_br_101                                              0.1214      0.017      7.112      0.000       0.088       0.155
km_br_116                                              0.0286      0.015      1.855      0.064      -0.002       0.059
km_br_153                                              0.0830      0.029      2.910      0.004       0.027       0.139
km_br_163                                              0.0332      0.021      1.599      0.110      -0.007       0.074
km_br_364                                              0.1990      0.027      7.372      0.000       0.146       0.252
pessoas                                               -0.2410      0.009    -25.715      0.000      -0.259      -0.223
veiculos                                              -0.0350      0.007     -4.816      0.000      -0.049      -0.021
0/1                                                    1.7475      0.035     50.275      0.000       1.679       1.816
1/2                                                    0.4111      0.005     88.461      0.000       0.402       0.420
======================================================================================================================

In [72]:
formula_modelo_2 = f"""
    km + {new} + pessoas + veiculos + C(uf) +
    C(fase_dia) + C(condicao_metereologica) +
    C(tipo_pista) + C(tracado_via) + C(uso_solo) +
    C(sentido_via) + C(tipo_acidente) + C(mes) + C(dia_semana_num) +
    C(causa_acidente)
"""

In [74]:
X2 = dmatrix(formula_modelo_2, df, return_type='dataframe')
X2.drop(columns=['Intercept'], inplace=True)

In [75]:
model = OrderedModel(y, X2, distr='logit')

In [76]:
iteration_counter = [0]
print("Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...")
print("="*60)
print(f"{'Iter':<3} | {'Neg. LL':<15} | {'Grad. Norm':<12}")
print("="*60)

fit_2 = model.fit(
    method='lbfgs', 
    callback=show_optimized_progress
)

print("="*60)
print("Ajuste concluído!")

Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...
============================================================
Iter | Neg. LL         | Grad. Norm
============================================================
Iter: 25  | Neg. LL: 168463.8684     | Grad. Norm: 538.212706
Iter: 50  | Neg. LL: 168188.6296     | Grad. Norm: 281.738194
Iter: 75  | Neg. LL: 168139.2400     | Grad. Norm: 147.977810
Iter: 100 | Neg. LL: 168121.7645     | Grad. Norm: 230.023097
Iter: 125 | Neg. LL: 168113.6298     | Grad. Norm: 89.924559
Iter: 150 | Neg. LL: 168110.7315     | Grad. Norm: 31.906345
Iter: 175 | Neg. LL: 168109.1435     | Grad. Norm: 59.732259
Iter: 200 | Neg. LL: 168108.1172     | Grad. Norm: 27.627507
Iter: 225 | Neg. LL: 168107.5977     | Grad. Norm: 49.151508
Iter: 250 | Neg. LL: 168107.0992     | Grad. Norm: 14.837424
Iter: 275 | Neg. LL: 168106.8935     | Grad. Norm: 16.580017
Iter: 300 | Neg. LL: 168106.6563     | Grad. Norm: 16.518576
============================================================
Ajuste concluído!

In [77]:
print(fit_2.summary())
fit_2.save("./results/inference2.pkl")

                             OrderedModel Results
==============================================================================
Dep. Variable:                      y   Log-Likelihood:            -1.6811e+05
Model:                   OrderedModel   AIC:                         3.366e+05
Method:            Maximum Likelihood   BIC:                         3.383e+05
Date:                Sat, 15 Nov 2025
Time:                        23:24:07
No. Observations:              258737
Df Residuals:                  258566
Df Model:                         169
=====================================================================================================================================================================
                                                                                                        coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
C(uf)[T.AC]                                                                                           0.6939      0.085      8.116      0.000       0.526       0.861
C(uf)[T.AL]                                                                                           0.7491      0.049     15.304      0.000       0.653       0.845
C(uf)[T.AP]                                                                                           0.4799      0.094      5.119      0.000       0.296       0.664
C(uf)[T.AM]                                                                                           0.6179      0.108      5.718      0.000       0.406       0.830
C(uf)[T.BA]                                                                                           0.5164      0.028     18.213      0.000       0.461       0.572
C(uf)[T.CE]                                                                                           0.7766      0.037     21.247      0.000       0.705       0.848
C(uf)[T.DF]                                                                                           0.0189      0.050      0.374      0.708      -0.080       0.118
C(uf)[T.ES]                                                                                           0.5397      0.033     16.249      0.000       0.475       0.605
C(uf)[T.GO]                                                                                           0.4663      0.031     14.817      0.000       0.405       0.528
C(uf)[T.MA]                                                                                           0.9239      0.037     24.741      0.000       0.851       0.997
C(uf)[T.MT]                                                                                           0.4086      0.038     10.700      0.000       0.334       0.483
C(uf)[T.MS]                                                                                           0.4783      0.039     12.381      0.000       0.403       0.554
C(uf)[T.MG]                                                                                           0.4238      0.025     17.265      0.000       0.376       0.472
C(uf)[T.PA]                                                                                           0.9004      0.041     21.931      0.000       0.820       0.981
C(uf)[T.PB]                                                                                           0.7506      0.035     21.670      0.000       0.683       0.818
C(uf)[T.PR]                                                                                           0.2952      0.025     11.803      0.000       0.246       0.344
C(uf)[T.PE]                                                                                           0.7621      0.030     25.666      0.000       0.704       0.820
C(uf)[T.PI]                                                                                           0.8806      0.036     24.602      0.000       0.810       0.951
C(uf)[T.RJ]                                                                                          -0.0031      0.028     -0.112      0.911      -0.058       0.051
C(uf)[T.RN]                                                                                           0.5946      0.038     15.818      0.000       0.521       0.668
C(uf)[T.RO]                                                                                           0.2882      0.050      5.710      0.000       0.189       0.387
C(uf)[T.RR]                                                                                           0.6571      0.091      7.184      0.000       0.478       0.836
C(uf)[T.SC]                                                                                           0.2523      0.026      9.858      0.000       0.202       0.302
C(uf)[T.SP]                                                                                           0.0504      0.031      1.649      0.099      -0.010       0.110
C(uf)[T.SE]                                                                                           0.6347      0.054     11.777      0.000       0.529       0.740
C(uf)[T.TO]                                                                                           0.6100      0.055     11.039      0.000       0.502       0.718
C(fase_dia)[T.Amanhecer]                                                                              0.2451      0.022     11.005      0.000       0.201       0.289
C(fase_dia)[T.Anoitecer]                                                                              0.1034      0.021      4.842      0.000       0.062       0.145
C(fase_dia)[T.Plena Noite]                                                                            0.2441      0.011     22.224      0.000       0.223       0.266
C(condicao_metereologica)[T.Nublado]                                                                 -0.0541      0.014     -3.943      0.000      -0.081      -0.027
C(condicao_metereologica)[T.Chuva]                                                                   -0.2268      0.019    -11.890      0.000      -0.264      -0.189
C(condicao_metereologica)[T.Garoa/Chuvisco]                                                          -0.3042      0.028    -10.702      0.000      -0.360      -0.248
C(condicao_metereologica)[T.Sol]                                                                      0.0233      0.022      1.078      0.281      -0.019       0.066
C(condicao_metereologica)[T.Ignorado]                                                                 0.1446      0.039      3.753      0.000       0.069       0.220
C(condicao_metereologica)[T.Nevoeiro/Neblina]                                                        -0.0053      0.052     -0.102      0.919      -0.107       0.096
C(condicao_metereologica)[T.Vento]                                                                    0.0214      0.113      0.188      0.851      -0.201       0.244
C(condicao_metereologica)[T.Granizo]                                                                 -0.5301      0.929     -0.571      0.568      -2.350       1.290
C(condicao_metereologica)[T.Neve]                                                                    -0.4856      1.462     -0.332      0.740      -3.352       2.381
C(tipo_pista)[T.Simples]                                                                              0.2174      0.012     18.384      0.000       0.194       0.241
C(tipo_pista)[T.Múltipla]                                                                            -0.0093      0.019     -0.485      0.628      -0.047       0.028
C(tracado_via)[T.Curva]                                                                              -0.0274      0.014     -2.001      0.045      -0.054      -0.001
C(tracado_via)[T.Aclive_Declive]                                                                     -0.0298      0.027     -1.088      0.277      -0.083       0.024
C(tracado_via)[T.Intersecao]                                                                         -0.2723      0.028     -9.719      0.000      -0.327      -0.217
C(tracado_via)[T.Especial]                                                                           -0.1023      0.052     -1.965      0.049      -0.204      -0.000
C(tracado_via)[T.Outro]                                                                              -0.3565      0.032    -10.992      0.000      -0.420      -0.293
C(uso_solo)[T.Sim]                                                                                   -0.1246      0.011    -11.523      0.000      -0.146      -0.103
C(sentido_via)[T.Crescente]                                                                           0.0358      0.010      3.748      0.000       0.017       0.055
C(sentido_via)[T.Não Informado]                                                                      -1.5602      0.164     -9.501      0.000      -1.882      -1.238
C(tipo_acidente)[T.Colisão traseira]                                                                 -0.0885      0.023     -3.915      0.000      -0.133      -0.044
C(tipo_acidente)[T.Colisão frontal]                                                                   1.0389      0.026     39.529      0.000       0.987       1.090
C(tipo_acidente)[T.Saída de leito carroçável]                                                        -0.1798      0.022     -8.323      0.000      -0.222      -0.137
C(tipo_acidente)[T.Colisão com objeto]                                                               -0.1418      0.026     -5.511      0.000      -0.192      -0.091
C(tipo_acidente)[T.Colisão lateral mesmo sentido]                                                    -0.3224      0.027    -12.144      0.000      -0.374      -0.270
C(tipo_acidente)[T.Engavetamento]                                                                    -1.4657      0.082    -17.772      0.000      -1.627      -1.304
C(tipo_acidente)[T.Colisão lateral sentido oposto]                                                   -0.0849      0.035     -2.457      0.014      -0.153      -0.017
C(tipo_acidente)[T.Colisão transversal]                                                               0.2752      0.026     10.397      0.000       0.223       0.327
C(tipo_acidente)[T.Capotamento]                                                                      -0.3392      0.040     -8.532      0.000      -0.417      -0.261
C(tipo_acidente)[T.Queda de ocupante de veículo]                                                      0.0967      0.028      3.436      0.001       0.042       0.152
C(tipo_acidente)[T.Incêndio]                                                                         -4.8698      0.290    -16.787      0.000      -5.438      -4.301
C(tipo_acidente)[T.Derramamento de carga]                                                            -1.0296      0.184     -5.588      0.000      -1.391      -0.668
C(tipo_acidente)[T.Atropelamento de Pedestre]                                                         1.0691      0.034     31.273      0.000       1.002       1.136
C(tipo_acidente)[T.Eventos atípicos]                                                                  0.0572      0.074      0.768      0.442      -0.089       0.203
C(tipo_acidente)[T.Atropelamento de Animal]                                                           0.1879      0.074      2.551      0.011       0.044       0.332
C(tipo_acidente)[T.Sinistro pessoal de trânsito]                                                      1.6256      0.472      3.448      0.001       0.701       2.550
C(mes)[T.2]                                                                                          -0.0445      0.024     -1.867      0.062      -0.091       0.002
C(mes)[T.3]                                                                                          -0.0502      0.023     -2.178      0.029      -0.095      -0.005
C(mes)[T.4]                                                                                          -0.0266      0.023     -1.155      0.248      -0.072       0.019
C(mes)[T.5]                                                                                          -0.0243      0.023     -1.065      0.287      -0.069       0.020
C(mes)[T.6]                                                                                          -0.0534      0.023     -2.335      0.020      -0.098      -0.009
C(mes)[T.7]                                                                                          -0.0622      0.023     -2.733      0.006      -0.107      -0.018
C(mes)[T.8]                                                                                          -0.0340      0.023     -1.491      0.136      -0.079       0.011
C(mes)[T.9]                                                                                          -0.0499      0.023     -2.177      0.030      -0.095      -0.005
C(mes)[T.10]                                                                                         -0.0219      0.024     -0.898      0.369      -0.070       0.026
C(mes)[T.11]                                                                                         -0.0185      0.025     -0.745      0.456      -0.067       0.030
C(mes)[T.12]                                                                                         -0.0499      0.024     -2.062      0.039      -0.097      -0.002
C(dia_semana_num)[T.2]                                                                               -0.0244      0.019     -1.301      0.193      -0.061       0.012
C(dia_semana_num)[T.3]                                                                               -0.0305      0.019     -1.631      0.103      -0.067       0.006
C(dia_semana_num)[T.4]                                                                               -0.0055      0.019     -0.295      0.768      -0.042       0.031
C(dia_semana_num)[T.5]                                                                                0.0246      0.018      1.389      0.165      -0.010       0.059
C(dia_semana_num)[T.6]                                                                                0.0775      0.017      4.464      0.000       0.043       0.112
C(dia_semana_num)[T.7]                                                                                0.0947      0.017      5.426      0.000       0.060       0.129
C(causa_acidente)[T.Condutor deixou de manter distância do veículo da frente]                         0.1545      0.033      4.628      0.000       0.089       0.220
C(causa_acidente)[T.Reação tardia ou ineficiente do condutor]                                         0.4413      0.026     16.803      0.000       0.390       0.493
C(causa_acidente)[T.Acumulo de água sobre o pavimento]                                                0.1524      0.068      2.226      0.026       0.018       0.287
C(causa_acidente)[T.Mal súbito do condutor]                                                           0.8832      0.056     15.892      0.000       0.774       0.992
C(causa_acidente)[T.Chuva]                                                                            0.3490      0.051      6.851      0.000       0.249       0.449
C(causa_acidente)[T.Ausência de reação do condutor]                                                   0.5829      0.026     22.449      0.000       0.532       0.634
C(causa_acidente)[T.Manobra de mudança de faixa]                                                      0.4057      0.032     12.562      0.000       0.342       0.469
C(causa_acidente)[T.Pista Escorregadia]                                                               0.1694      0.065      2.602      0.009       0.042       0.297
C(causa_acidente)[T.Ausência de sinalização]                                                          0.5291      0.087      6.076      0.000       0.358       0.700
C(causa_acidente)[T.Condutor Dormindo]                                                                0.4036      0.036     11.343      0.000       0.334       0.473
C(causa_acidente)[T.Velocidade Incompatível]                                                          0.8242      0.029     28.051      0.000       0.767       0.882
C(causa_acidente)[T.Acessar a via sem observar a presença dos outros veículos]                        0.4996      0.029     16.995      0.000       0.442       0.557
C(causa_acidente)[T.Conversão proibida]                                                               0.4938      0.045     10.993      0.000       0.406       0.582
C(causa_acidente)[T.Transitar na contramão]                                                           0.7192      0.033     22.074      0.000       0.655       0.783
C(causa_acidente)[T.Ultrapassagem Indevida]                                                           0.7080      0.036     19.598      0.000       0.637       0.779
C(causa_acidente)[T.Desrespeitar a preferência no cruzamento]                                         0.4033      0.043      9.304      0.000       0.318       0.488
C(causa_acidente)[T.Acostamento em desnível]                                                          0.0205      0.106      0.194      0.846      -0.187       0.228
C(causa_acidente)[T.Demais falhas mecânicas ou elétricas]                                             0.1657      0.041      4.032      0.000       0.085       0.246
C(causa_acidente)[T.Carga excessiva e/ou mal acondicionada]                                          -0.0599      0.102     -0.588      0.557      -0.260       0.140
C(causa_acidente)[T.Problema com o freio]                                                             0.4192      0.091      4.610      0.000       0.241       0.597
C(causa_acidente)[T.Ingestão de álcool e/ou substâncias psicoativas pelo pedestre]                    0.2229      0.105      2.124      0.034       0.017       0.429
C(causa_acidente)[T.Curva acentuada]                                                                  0.4892      0.087      5.651      0.000       0.320       0.659
C(causa_acidente)[T.Estacionar ou parar em local proibido]                                            0.6945      0.095      7.318      0.000       0.509       0.881
C(causa_acidente)[T.Avarias e/ou desgaste excessivo no pneu]                                          0.2420      0.046      5.216      0.000       0.151       0.333
C(causa_acidente)[T.Pedestre cruzava a pista fora da faixa]                                           0.7411      0.053     14.097      0.000       0.638       0.844
C(causa_acidente)[T.Obstrução na via]                                                                 0.7300      0.210      3.480      0.001       0.319       1.141
C(causa_acidente)[T.Acesso irregular]                                                                 0.5201      0.048     10.743      0.000       0.425       0.615
C(causa_acidente)[T.Pista esburacada]                                                                 0.4480      0.070      6.394      0.000       0.311       0.585
C(causa_acidente)[T.Animais na Pista]                                                                 0.2371      0.072      3.299      0.001       0.096       0.378
C(causa_acidente)[T.Falta de acostamento]                                                             0.7378      0.136      5.435      0.000       0.472       1.004
C(causa_acidente)[T.Entrada inopinada do pedestre]                                                    0.6631      0.050     13.305      0.000       0.565       0.761
C(causa_acidente)[T.Acumulo de areia ou detritos sobre o pavimento]                                   0.1798      0.086      2.099      0.036       0.012       0.348
C(causa_acidente)[T.Pedestre andava na pista]                                                         0.7778      0.050     15.575      0.000       0.680       0.876

In [131]:
df_sample = df.sample(n=65000, random_state=42)

In [132]:
df_sample

,uf,br,km,causa_acidente,tipo_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,...,km_br_101,br_116,km_br_116,br_153,km_br_153,br_163,km_br_163,br_364,km_br_364,risco_ordenado
58363,MG,365,-0.418749,Reação tardia ou ineficiente do condutor,Colisão traseira,Anoitecer,Crescente,Ignorado,Simples,Reta,...,-0.000000,0,-0.0,0,-0.000000,0,-0.0,0,-0.0,medio
129547,GO,153,0.502191,Reação tardia ou ineficiente do condutor,Colisão traseira,Pleno dia,Crescente,Céu Claro,Simples,Reta,...,0.000000,0,0.0,1,0.502191,0,0.0,0,0.0,baixo
186289,PR,369,-0.383497,Transtornos Mentais (exceto suicidio),Queda de ocupante de veículo,Pleno dia,Decrescente,Céu Claro,Simples,Reta,...,-0.000000,0,-0.0,0,-0.000000,0,-0.0,0,-0.0,baixo
152990,SC,282,1.008928,Ingestão de álcool pelo condutor,Colisão traseira,Plena Noite,Crescente,Céu Claro,Simples,Outro,...,0.000000,0,0.0,0,0.000000,0,0.0,0,0.0,baixo
10936,RJ,101,0.898768,Mal súbito do condutor,Colisão frontal,Pleno dia,Crescente,Nublado,Simples,Reta,...,0.898768,0,0.0,0,0.000000,0,0.0,0,0.0,baixo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119460,ES,101,0.167304,Trafegar com motocicleta (ou similar) entre as...,Queda de ocupante de veículo,Plena Noite,Decrescente,Céu Claro,Dupla,Reta,...,0.167304,0,0.0,0,0.000000,0,0.0,0,0.0,baixo
164573,MG,40,0.793014,Velocidade Incompatível,Saída de leito carroçável,Pleno dia,Crescente,Céu Claro,Dupla,Reta,...,0.000000,0,0.0,0,0.000000,0,0.0,0,0.0,baixo
243553,SC,101,-0.938705,Trafegar com motocicleta (ou similar) entre as...,Colisão traseira,Pleno dia,Crescente,Céu Claro,Dupla,Reta,...,-0.938705,0,-0.0,0,-0.000000,0,-0.0,0,-0.0,baixo
15346,PR,373,-0.246899,Condutor Dormindo,Colisão lateral sentido oposto,Pleno dia,Crescente,Céu Claro,Simples,Reta,...,-0.000000,0,-0.0,0,-0.000000,0,-0.0,0,-0.0,baixo
195061,MG,40,0.691666,Transitar no Acostamento,Atropelamento de Pedestre,Plena Noite,Decrescente,Ignorado,Simples,Reta,...,0.000000,0,0.0,0,0.000000,0,0.0,0,0.0,medio

In [133]:
formula_modelo_3 = f"""
    km + {new} + pessoas + veiculos + C(uf) +
    C(fase_dia) + C(condicao_metereologica) +
    C(tipo_pista) + C(tracado_via) + C(uso_solo) +
    C(tipo_acidente) + C(mes) + C(dia_semana_num) +
    C(causa_acidente) +
    C(causa_acidente) * C(fase_dia) +
    C(causa_acidente) * C(tipo_pista) +
    C(tipo_pista) * C(tracado_via)
    
"""
#   C(sentido_via)

In [134]:
X3 = dmatrix(formula_modelo_3, df_sample, return_type='dataframe')
X3.drop(columns=['Intercept'], inplace=True)

In [135]:
X3

,C(uf)[T.AC],C(uf)[T.AL],C(uf)[T.AP],C(uf)[T.AM],C(uf)[T.BA],C(uf)[T.CE],C(uf)[T.DF],C(uf)[T.ES],C(uf)[T.GO],C(uf)[T.MA],...,br_153,br_163,br_364,km_br_101,km_br_116,km_br_153,km_br_163,km_br_364,pessoas,veiculos
58363,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,-0.000000,-0.0,-0.000000,-0.0,-0.0,0.184851,0.007886
129547,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.000000,0.0,0.502191,0.0,0.0,0.636918,0.889690
186289,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,-0.000000,-0.0,-0.000000,-0.0,-0.0,-0.267216,-0.873917
152990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.184851,0.007886
10936,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.898768,0.0,0.000000,0.0,0.0,0.184851,0.889690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.167304,0.0,0.000000,0.0,0.0,0.184851,0.007886
164573,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,1.088985,-0.873917
243553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,-0.938705,-0.0,-0.000000,-0.0,-0.0,0.184851,0.007886
15346,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,-0.000000,-0.0,-0.000000,-0.0,-0.0,0.184851,1.771494
195061,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,-0.267216,0.007886

In [136]:
y_sample_aligned = y[X3.index]

In [137]:
iteration_counter = [0]
model = OrderedModel(y_sample_aligned, X3, distr='logit')

In [ ]:
DEBUG_MODE = False
iteration_counter = [0]
print("Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...")
print("="*60)
print(f"{'Iter':<3} | {'Neg. LL':<15} | {'Grad. Norm':<12}")
print("="*60)

fit_3 = model.fit(
        method='lbfgs', 
        callback=show_optimized_progress,
        maxiter=1000 # Dando um pouco mais de "corda" para o modelo complexo
    )

print("="*60)
print("Ajuste concluído!")

Iniciando o ajuste do modelo (Modo Diagnóstico Lento)...
============================================================
Iter | Neg. LL         | Grad. Norm
============================================================
Iter: 25  | Neg. LL: 42092.1813      | Grad. Norm: 188.717649
Iter: 50  | Neg. LL: 41981.3514      | Grad. Norm: 114.740926
Iter: 75  | Neg. LL: 41940.7582      | Grad. Norm: 90.042553