# Predição de Risco de Acidentes

Este notebook tem como objetivo criar um modelo preditivo para o risco de acidentes (`baixo`, `medio`, `alto`), com foco na classe de alto risco.

## Passos:
1. Carregamento e Preparação dos Dados
2. Separação de Dados de Validação (20%)
3. Pipelines de Pré-processamento
4. Tunning de Hiperparâmetros com Optuna (Logistic Regression vs LightGBM)
5. Avaliação dos Modelos (Separada)

In [198]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import optuna
import joblib
import warnings

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder, LabelEncoder, label_binarize, TargetEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score, accuracy_score, make_scorer, roc_curve, auc, precision_recall_curve
import lightgbm as lgb

optuna.logging.set_verbosity(optuna.logging.INFO)
warnings.filterwarnings('ignore')

## 1. Carregamento e Preparação dos Dados

In [199]:
# Carregar dados com Polars
df_pl = pl.read_parquet("data/anuario_prf.parquet")

# Converter para Pandas
df = df_pl.to_pandas()

# Visualizar primeiras linhas
df.head()

,uf,br,km,causa_acidente,tipo_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,veiculos,latitude,longitude,risco,data,mes,dia_semana_num
0,PR,116,33,Ingestão de álcool pelo condutor,Tombamento,Pleno dia,Decrescente,Nublado,Dupla,Curva,Não,3,2,-25.114403,-48.846755,alto,2022-01-01,1,6
1,MS,163,393,Condutor deixou de manter distância do veículo...,Colisão traseira,Amanhecer,Decrescente,Céu Claro,Simples,Aclive_Declive,Não,3,3,-21.228445,-54.456296,medio,2022-01-01,1,6
2,RJ,101,457,Reação tardia ou ineficiente do condutor,Colisão frontal,Pleno dia,Decrescente,Chuva,Simples,Curva,Sim,2,2,-23.031498,-44.177153,alto,2022-01-01,1,6
3,MG,40,508,Acumulo de água sobre o pavimento,Saída de leito carroçável,Pleno dia,Decrescente,Chuva,Dupla,Reta,Sim,3,1,-19.760612,-44.134754,baixo,2022-01-01,1,6
4,PB,116,8,Mal súbito do condutor,Colisão com objeto,Pleno dia,Crescente,Céu Claro,Simples,Reta,Não,3,2,-6.964668,-38.727608,baixo,2022-01-01,1,6

In [200]:
# Verificar tipos e nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258737 entries, 0 to 258736
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   uf                      258737 non-null  category
 1   br                      258737 non-null  category
 2   km                      258737 non-null  int64
 3   causa_acidente          258737 non-null  category
 4   tipo_acidente           258737 non-null  category
 5   fase_dia                258737 non-null  category
 6   sentido_via             258737 non-null  category
 7   condicao_metereologica  258737 non-null  category
 8   tipo_pista              258737 non-null  category
 9   tracado_via             258737 non-null  category
 10  uso_solo                258737 non-null  category
 11  pessoas                 258737 non-null  int64
 12  veiculos                258737 non-null  int64
 13  latitude                258737 non-null  float64
 14  longitude               258737 non-null  float64
 15  risco                   258737 non-null  category
 16  data                    258737 non-null  datetime64[ms]
 17  mes                     258737 non-null  int8
 18  dia_semana_num          258737 non-null  int8
dtypes: category(11), datetime64[ms](1), float64(2), int64(3), int8(2)
memory usage: 15.1 MB

In [201]:
df.drop(columns=['causa_acidente','veiculos', 'pessoas', 'tipo_acidente'], inplace=True)

In [140]:
df

,uf,br,km,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,latitude,longitude,risco,data,mes,dia_semana_num
0,PR,116,33,Pleno dia,Decrescente,Nublado,Dupla,Curva,Não,-25.114403,-48.846755,alto,2022-01-01,1,6
1,MS,163,393,Amanhecer,Decrescente,Céu Claro,Simples,Aclive_Declive,Não,-21.228445,-54.456296,baixo,2022-01-01,1,6
2,RJ,101,457,Pleno dia,Decrescente,Chuva,Simples,Curva,Sim,-23.031498,-44.177153,medio,2022-01-01,1,6
3,MG,40,508,Pleno dia,Decrescente,Chuva,Dupla,Reta,Sim,-19.760612,-44.134754,baixo,2022-01-01,1,6
4,PB,116,8,Pleno dia,Crescente,Céu Claro,Simples,Reta,Não,-6.964668,-38.727608,baixo,2022-01-01,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258732,SC,282,302,Pleno dia,Crescente,Céu Claro,Simples,Reta,Não,-27.519538,-50.909615,medio,2025-09-27,9,6
258733,SP,381,82,Pleno dia,Crescente,Céu Claro,Múltipla,Reta,Sim,-23.481235,-46.562748,baixo,2025-08-30,8,6
258734,RJ,493,20,Pleno dia,Crescente,Sol,Simples,Curva,Não,-22.660571,-43.046321,medio,2025-08-25,8,1
258735,SC,101,321,Plena Noite,Crescente,Céu Claro,Dupla,Reta,Sim,-28.428350,-48.914460,medio,2025-09-28,9,7
258736,AL,316,189,Plena Noite,Decrescente,Céu Claro,Simples,Curva,Não,-9.583395,-36.419045,medio,2025-08-30,8,6

In [175]:
df['dia_semana_num']

0         6
1         6
2         6
3         6
4         6
         ..
258732    6
258733    6
258734    1
258735    7
258736    6
Name: dia_semana_num, Length: 258737, dtype: int8

In [202]:
def criar_features_transito(df):
    df = df.copy()
    
    df['lat_cluster'] = df['latitude'].round(3).astype(str) + '_' + df['longitude'].round(3).astype(str)
    
    df['trecho_br'] = df['br'].astype(str) + '_' + (df['km'] // 10).astype(str)
    
    df['hora'] = df['data'].dt.hour
    
    df['mes_sin'] = np.sin(2 * np.pi * df['mes']/12)
    df['mes_cos'] = np.cos(2 * np.pi * df['mes']/12)
    
    df['sem_sin'] = np.sin(2 * np.pi * df['dia_semana_num']/7)
    df['sem_cos'] = np.cos(2 * np.pi * df['dia_semana_num']/7)
    
    df['is_weekend'] = df['dia_semana_num'].isin([5, 6, 7]).astype(int) # Ajuste conforme sua numeração (0-6 ou 1-7)
    
    df['pista_sentido'] = df['tipo_pista'].astype(str) + '_' + df['sentido_via'].astype(str)
    
    df['clima_tracado'] = df['condicao_metereologica'].astype(str) + '_' + df['tracado_via'].astype(str)
    
    return df

## 2. Separação de Dados de Validação

In [203]:
df_tratada = criar_features_transito(df)
X = df_tratada.drop(columns=['risco'])
y = df_tratada['risco']

In [204]:
df_tratada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258737 entries, 0 to 258736
Data columns (total 25 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   uf                      258737 non-null  category
 1   br                      258737 non-null  category
 2   km                      258737 non-null  int64
 3   fase_dia                258737 non-null  category
 4   sentido_via             258737 non-null  category
 5   condicao_metereologica  258737 non-null  category
 6   tipo_pista              258737 non-null  category
 7   tracado_via             258737 non-null  category
 8   uso_solo                258737 non-null  category
 9   latitude                258737 non-null  float64
 10  longitude               258737 non-null  float64
 11  risco                   258737 non-null  category
 12  data                    258737 non-null  datetime64[ms]
 13  mes                     258737 non-null  int8
 14  dia_semana_num          258737 non-null  int8
 15  lat_cluster             258737 non-null  object
 16  trecho_br               258737 non-null  object
 17  hora                    258737 non-null  int32
 18  mes_sin                 258737 non-null  float64
 19  mes_cos                 258737 non-null  float64
 20  sem_sin                 258737 non-null  float64
 21  sem_cos                 258737 non-null  float64
 22  is_weekend              258737 non-null  int64
 23  pista_sentido           258737 non-null  object
 24  clima_tracado           258737 non-null  object
dtypes: category(9), datetime64[ms](1), float64(6), int32(1), int64(2), int8(2), object(4)
memory usage: 29.4+ MB

In [205]:

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.40, stratify=y, random_state=42
)

# Segundo: Dividir Temp em 50% Validação e 50% Teste (15% do total cada)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42
)

# Salvar conjuntos
val_df = pd.concat([X_val, y_val], axis=1)
pl.from_pandas(val_df).write_parquet("data/validação.parquet")
test_df = pd.concat([X_test, y_test], axis=1)
pl.from_pandas(test_df).write_parquet("data/teste.parquet")

print(f"Treino shape: {X_train.shape}")
print(f"Validação shape: {X_val.shape}")
print(f"Teste shape: {X_test.shape}")

Treino shape: (155242, 24)
Validação shape: (51747, 24)
Teste shape: (51748, 24)

In [206]:
y_train_s1 = y_train.apply(lambda x: 0 if x == 'baixo' else 1)
y_val_s1 = y_val.apply(lambda x: 0 if x == 'baixo' else 1)

# Estágio 2: Médio (0) vs Alto (1) - Apenas para dados que NÃO são Baixo
# Filtrar dados de treino onde y original != 0
mask_train_s2 = y_train != 'baixo'
X_train_s2 = X_train[mask_train_s2]
y_train_s2 = y_train[mask_train_s2].map({'medio': 0, 'alto': 1}) # Mapear Médio->0, Alto->1

# Filtrar dados de validação (para uso no Optuna)
mask_val_s2 = y_val != 'baixo'
X_val_s2 = X_val[mask_val_s2]
y_val_s2 = y_val[mask_val_s2].map({'medio': 0, 'alto': 1})

print("Distribuição Estágio 1 (Treino):", y_train_s1.value_counts(normalize=True).to_dict())
print("Distribuição Estágio 2 (Treino):", y_train_s2.value_counts(normalize=True).to_dict())

Distribuição Estágio 1 (Treino): {1: 0.836004431790366, 0: 0.16399556820963399}
Distribuição Estágio 2 (Treino): {0.0: 0.6612345222409715, 1.0: 0.33876547775902854}

In [207]:
#Identificar colunas numéricas e categóricas
categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
numerical_cols = X_train.select_dtypes(include=['number']).columns.tolist()
numerical_cols.remove('hora')
categorical_cols.append('hora')

print("Numéricas:", numerical_cols)
print("Categóricas:", categorical_cols)

# Preprocessamento para Regressão Logística
numeric_transformer_lr = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer_lr = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', TargetEncoder())
])

preprocessor_lr = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer_lr, numerical_cols),
        ('cat', categorical_transformer_lr, categorical_cols)
    ])

# Preprocessamento para LightGBM
numeric_transformer_lgbm = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
])

categorical_transformer_lgbm = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('target_enc', TargetEncoder())
])

preprocessor_lgbm = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer_lgbm, numerical_cols),
        ('cat', categorical_transformer_lgbm, categorical_cols)
    ])

Numéricas: ['km', 'latitude', 'longitude', 'mes', 'dia_semana_num', 'mes_sin', 'mes_cos', 'sem_sin', 'sem_cos', 'is_weekend']
Categóricas: ['uf', 'br', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'lat_cluster', 'trecho_br', 'pista_sentido', 'clima_tracado', 'hora']

In [193]:
def objective_lr_s1(trial):
    # Estágio 1: Baixo vs Resto
    C = trial.suggest_loguniform('C', 1e-3, 100)
    solver = trial.suggest_categorical('solver', ['lbfgs'])
    class_weight = trial.suggest_categorical('class_weight', ['balanced', None])
    
    model = LogisticRegression(C=C, solver=solver, class_weight=class_weight, max_iter=1000, random_state=42)
    clf = Pipeline(steps=[('preprocessor', preprocessor_lr), ('classifier', model)])
    
    # F1 Macro para classificação binária
    score = cross_val_score(clf, X_train, y_train_s1, cv=5, scoring='accuracy', n_jobs=-1).mean()
    return score

def objective_lr_s2(trial):
    # Estágio 2: Médio vs Alto
    C = trial.suggest_loguniform('C', 1e-3, 100)
    solver = trial.suggest_categorical('solver', ['lbfgs'])
    class_weight = trial.suggest_categorical('class_weight', ['balanced', None])
    
    model = LogisticRegression(C=C, solver=solver, class_weight=class_weight, max_iter=1000, random_state=42)
    clf = Pipeline(steps=[('preprocessor', preprocessor_lr), ('classifier', model)])
    
    # F1 Macro para classificação binária
    score = cross_val_score(clf, X_train_s2, y_train_s2, cv=5, scoring='f1_macro', n_jobs=-1).mean()
    return score

In [196]:
def objective_lgbm_s1(trial):
    params = {
        'objective': 'binary',
        'metric': 'binary_logloss',
        'verbosity': -1,
        'n_jobs': 1,
        'boosting_type': 'gbdt',
        'random_state': 42,
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.1),
        'num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'class_weight': trial.suggest_categorical('class_weight', ['balanced'])
    }
    
    model = lgb.LGBMClassifier(**params)
    clf = Pipeline(steps=[('preprocessor', preprocessor_lgbm), ('classifier', model)])
    
    score = cross_val_score(clf, X_train, y_train_s1, cv=5, scoring='f1', n_jobs=-1).mean()
    return score

def objective_lgbm_s2(trial):
    params = {
        'objective': 'binary',
        'metric': 'binary_logloss',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'random_state': 42,
        'n_jobs': 1,
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.1),
        'num_leaves': trial.suggest_int('num_leaves', 20, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'class_weight': trial.suggest_categorical('class_weight', ['balanced'])
    }
    
    model = lgb.LGBMClassifier(**params)
    clf = Pipeline(steps=[('preprocessor', preprocessor_lgbm), ('classifier', model)])
    
    score = cross_val_score(clf, X_train_s2, y_train_s2, cv=5, scoring='f1', n_jobs=-1).mean()
    return score

In [165]:
# Otimização LR
print("Otimizando LR Estágio 1...")
study_lr_s1 = optuna.create_study(direction='maximize')
study_lr_s1.optimize(objective_lr_s1, n_trials=40)

print("Otimizando LR Estágio 2...")
study_lr_s2 = optuna.create_study(direction='maximize')
study_lr_s2.optimize(objective_lr_s2, n_trials=40)

[I 2025-11-24 21:36:36,926] A new study created in memory with name: no-name-6c1054de-56e8-4716-b2fe-50276659422a

Otimizando LR Estágio 1...

[I 2025-11-24 21:36:45,224] Trial 0 finished with value: 0.6181445876678591 and parameters: {'C': 13.607873269611627, 'solver': 'lbfgs', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.6181445876678591.
[W 2025-11-24 21:36:47,340] Trial 1 failed with parameters: {'C': 0.0031636061902586064, 'solver': 'lbfgs', 'class_weight': 'balanced'} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_190709/3626814939.py", line 11, in objective_lr_s1
    score = cross_val_score(clf, X_train, y_train_s1, cv=5, scoring='accuracy', n_jobs=-1).mean()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 677, in cross_val_score
    cv_results = cross_validate(
                 ^^^^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 399, in cross_validate
    results = parallel(
              ^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/home/aderson/miniconda3/envs/dengue/lib/python3.12/site-packages/joblib/parallel.py", line 1800, in _retrieve
    time.sleep(0.01)
KeyboardInterrupt
[W 2025-11-24 21:36:47,342] Trial 1 failed with value None.

KeyboardInterrupt:

In [208]:
# Otimização LGBM
print("Otimizando LGBM Estágio 1...")
study_lgbm_s1 = optuna.create_study(direction='maximize')
study_lgbm_s1.optimize(objective_lgbm_s1, n_trials=20)

print("Otimizando LGBM Estágio 2...")
study_lgbm_s2 = optuna.create_study(direction='maximize')
study_lgbm_s2.optimize(objective_lgbm_s2, n_trials=20)

[I 2025-11-24 21:53:51,169] A new study created in memory with name: no-name-9a19dc52-f3de-444c-a088-dfe455365095

Otimizando LGBM Estágio 1...

[I 2025-11-24 21:54:01,184] Trial 0 finished with value: 0.6507624303160222 and parameters: {'learning_rate': 0.00561320530218321, 'num_leaves': 140, 'max_depth': 3, 'n_estimators': 90, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.6507624303160222.
[I 2025-11-24 21:54:19,203] Trial 1 finished with value: 0.7165337235674898 and parameters: {'learning_rate': 0.010689236051417276, 'num_leaves': 212, 'max_depth': 6, 'n_estimators': 321, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7165337235674898.
[I 2025-11-24 21:54:44,565] Trial 2 finished with value: 0.7000005143420271 and parameters: {'learning_rate': 0.0011050020583537584, 'num_leaves': 150, 'max_depth': 9, 'n_estimators': 382, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7165337235674898.
[I 2025-11-24 21:54:59,705] Trial 3 finished with value: 0.710056219909234 and parameters: {'learning_rate': 0.01280774192064632, 'num_leaves': 30, 'max_depth': 9, 'n_estimators': 473, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7165337235674898.
[I 2025-11-24 21:55:15,622] Trial 4 finished with value: 0.757130203496779 and parameters: {'learning_rate': 0.03497821209017515, 'num_leaves': 94, 'max_depth': 10, 'n_estimators': 396, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.757130203496779.
[I 2025-11-24 21:55:22,522] Trial 5 finished with value: 0.7011751036759455 and parameters: {'learning_rate': 0.03691588076337801, 'num_leaves': 190, 'max_depth': 3, 'n_estimators': 124, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.757130203496779.
[I 2025-11-24 21:55:37,354] Trial 6 finished with value: 0.7318925191173047 and parameters: {'learning_rate': 0.034873337651003984, 'num_leaves': 42, 'max_depth': 10, 'n_estimators': 474, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.757130203496779.
[I 2025-11-24 21:55:47,073] Trial 7 finished with value: 0.7005694172687366 and parameters: {'learning_rate': 0.011529054673274594, 'num_leaves': 33, 'max_depth': 3, 'n_estimators': 300, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.757130203496779.
[I 2025-11-24 21:56:14,619] Trial 8 finished with value: 0.8419325780878932 and parameters: {'learning_rate': 0.07621477990370076, 'num_leaves': 240, 'max_depth': 11, 'n_estimators': 497, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8419325780878932.
[I 2025-11-24 21:56:25,562] Trial 9 finished with value: 0.7400415665766752 and parameters: {'learning_rate': 0.08856529074215265, 'num_leaves': 24, 'max_depth': 7, 'n_estimators': 441, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8419325780878932.
[I 2025-11-24 21:56:42,814] Trial 10 finished with value: 0.7043117966048388 and parameters: {'learning_rate': 0.0021566748041573036, 'num_leaves': 300, 'max_depth': 12, 'n_estimators': 212, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8419325780878932.
[I 2025-11-24 21:56:56,240] Trial 11 finished with value: 0.7882101869285493 and parameters: {'learning_rate': 0.07496741223585991, 'num_leaves': 95, 'max_depth': 12, 'n_estimators': 391, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8419325780878932.
[I 2025-11-24 21:57:17,691] Trial 12 finished with value: 0.8475972955452471 and parameters: {'learning_rate': 0.09652213534159172, 'num_leaves': 262, 'max_depth': 12, 'n_estimators': 381, 'class_weight': 'balanced'}. Best is trial 12 with value: 0.8475972955452471.
[I 2025-11-24 21:57:46,434] Trial 13 finished with value: 0.8606887042376761 and parameters: {'learning_rate': 0.09900394587183242, 'num_leaves': 278, 'max_depth': 12, 'n_estimators': 495, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:58:08,296] Trial 14 finished with value: 0.7687182879538611 and parameters: {'learning_rate': 0.0226161020358154, 'num_leaves': 300, 'max_depth': 12, 'n_estimators': 230, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:58:22,562] Trial 15 finished with value: 0.7578098303790732 and parameters: {'learning_rate': 0.09966355852745122, 'num_leaves': 243, 'max_depth': 6, 'n_estimators': 344, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:58:49,278] Trial 16 finished with value: 0.8096854566639478 and parameters: {'learning_rate': 0.04971690602412208, 'num_leaves': 271, 'max_depth': 10, 'n_estimators': 420, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:59:04,994] Trial 17 finished with value: 0.7206366833021524 and parameters: {'learning_rate': 0.005649527842427753, 'num_leaves': 261, 'max_depth': 8, 'n_estimators': 246, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:59:28,211] Trial 18 finished with value: 0.7652667604026083 and parameters: {'learning_rate': 0.02105018160668982, 'num_leaves': 196, 'max_depth': 11, 'n_estimators': 359, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:59:52,196] Trial 19 finished with value: 0.8254521318273873 and parameters: {'learning_rate': 0.054937306335616366, 'num_leaves': 226, 'max_depth': 11, 'n_estimators': 441, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8606887042376761.
[I 2025-11-24 21:59:52,200] A new study created in memory with name: no-name-d1907f58-4272-4a9f-ab93-035de82cd18d

Otimizando LGBM Estágio 2...

[I 2025-11-24 22:00:06,262] Trial 0 finished with value: 0.5064782454719688 and parameters: {'learning_rate': 0.04387957937772512, 'num_leaves': 232, 'max_depth': 4, 'n_estimators': 299, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:00:22,050] Trial 1 finished with value: 0.4999361877867214 and parameters: {'learning_rate': 0.0019237532281892184, 'num_leaves': 222, 'max_depth': 8, 'n_estimators': 290, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:00:42,775] Trial 2 finished with value: 0.5000539342471548 and parameters: {'learning_rate': 0.01804331441118457, 'num_leaves': 195, 'max_depth': 8, 'n_estimators': 419, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:00:51,340] Trial 3 finished with value: 0.5054939034505358 and parameters: {'learning_rate': 0.021728892052637717, 'num_leaves': 66, 'max_depth': 11, 'n_estimators': 166, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:01:19,825] Trial 4 finished with value: 0.47243062979770245 and parameters: {'learning_rate': 0.0421039407547293, 'num_leaves': 295, 'max_depth': 12, 'n_estimators': 442, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:01:30,153] Trial 5 finished with value: 0.49729335033655947 and parameters: {'learning_rate': 0.00174369003297812, 'num_leaves': 245, 'max_depth': 6, 'n_estimators': 176, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:01:46,074] Trial 6 finished with value: 0.5060563967302635 and parameters: {'learning_rate': 0.014150888186940082, 'num_leaves': 28, 'max_depth': 12, 'n_estimators': 462, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:01:53,379] Trial 7 finished with value: 0.48281402072756335 and parameters: {'learning_rate': 0.0012010241376377566, 'num_leaves': 62, 'max_depth': 3, 'n_estimators': 143, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:02:20,665] Trial 8 finished with value: 0.4935893712435667 and parameters: {'learning_rate': 0.021444719363424524, 'num_leaves': 176, 'max_depth': 12, 'n_estimators': 466, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:02:42,466] Trial 9 finished with value: 0.5034266028000778 and parameters: {'learning_rate': 0.0033943050163287554, 'num_leaves': 112, 'max_depth': 8, 'n_estimators': 402, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.5064782454719688.
[I 2025-11-24 22:02:51,055] Trial 10 finished with value: 0.5067658073766269 and parameters: {'learning_rate': 0.09916976010224225, 'num_leaves': 296, 'max_depth': 3, 'n_estimators': 298, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:02:59,226] Trial 11 finished with value: 0.5061173625890213 and parameters: {'learning_rate': 0.09341094590511538, 'num_leaves': 299, 'max_depth': 3, 'n_estimators': 296, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:09,127] Trial 12 finished with value: 0.5019381147567042 and parameters: {'learning_rate': 0.08237727889919876, 'num_leaves': 256, 'max_depth': 5, 'n_estimators': 341, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:17,083] Trial 13 finished with value: 0.5055256981091432 and parameters: {'learning_rate': 0.0455574342833848, 'num_leaves': 253, 'max_depth': 5, 'n_estimators': 237, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:27,531] Trial 14 finished with value: 0.5044925597765696 and parameters: {'learning_rate': 0.005799204412271056, 'num_leaves': 129, 'max_depth': 4, 'n_estimators': 345, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:36,993] Trial 15 finished with value: 0.5028453752709394 and parameters: {'learning_rate': 0.04486515862707258, 'num_leaves': 212, 'max_depth': 6, 'n_estimators': 239, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:45,410] Trial 16 finished with value: 0.5061493776235473 and parameters: {'learning_rate': 0.0697720165789708, 'num_leaves': 281, 'max_depth': 3, 'n_estimators': 361, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:03:52,534] Trial 17 finished with value: 0.5026312989042475 and parameters: {'learning_rate': 0.007691272626975955, 'num_leaves': 155, 'max_depth': 10, 'n_estimators': 88, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:04:00,925] Trial 18 finished with value: 0.5057146121295647 and parameters: {'learning_rate': 0.027962569507239656, 'num_leaves': 268, 'max_depth': 5, 'n_estimators': 234, 'class_weight': 'balanced'}. Best is trial 10 with value: 0.5067658073766269.
[I 2025-11-24 22:04:09,670] Trial 19 finished with value: 0.5067679497584885 and parameters: {'learning_rate': 0.05122754008051305, 'num_leaves': 232, 'max_depth': 4, 'n_estimators': 308, 'class_weight': 'balanced'}. Best is trial 19 with value: 0.5067679497584885.

In [117]:
def hierarchical_predict(model_s1, model_s2, X):
    # Previsão Estágio 1: 0 (Baixo) vs 1 (Resto)
    pred_s1 = model_s1.predict(X)
    
    # Inicializar array final com 0 (Baixo)
    final_preds = np.zeros_like(pred_s1)
    
    # Identificar índices onde a previsão foi 'Resto' (1)
    mask_resto = (pred_s1 == 1)
    
    if np.any(mask_resto):
        # Previsão Estágio 2 apenas para esses casos: 0 (Médio) vs 1 (Alto)
        X_resto = X[mask_resto]
        pred_s2 = model_s2.predict(X_resto)
        
        # Mapear de volta: 0->1 (Médio), 1->2 (Alto)
        final_preds[mask_resto] = pred_s2 + 1
        
    return final_preds

In [118]:
def evaluate_hierarchical(model_s1, model_s2, X_test, y_test, name):
    print(f"--- Avaliação Hierárquica: {name} ---")
    
    # Gera as previsões (que retornam ints 0, 1, 2)
    y_pred = hierarchical_predict(model_s1, model_s2, X_test)
    
    # --- CORREÇÃO: Tratamento do y_test ---
    # Se y_test não for numérico, precisamos converter
    y_test_proc = y_test.copy()
    
    # Verifica se é do tipo objeto/string e converte
    if y_test_proc.dtype == 'object':
        # Mapeamento manual (garante que 'baixo' seja 0, etc.)
        # Ajuste as chaves aqui se seus labels originais forem diferentes (ex: "Baixo", "LOW", etc)
        mapping = {'baixo': 0, 'medio': 1, 'alto': 2}
        
        # Se o y_test for apenas strings de números ("0", "1"), o map retornará NaN, 
        # então usamos um try/except ou verificação direta.
        try:
            # Tenta mapear nomes para números
            if set(mapping.keys()).intersection(set(y_test_proc.unique())):
                y_test_proc = y_test_proc.map(mapping)
            else:
                # Se não tiver as chaves, tenta converter direto (caso sejam strings "0", "1")
                y_test_proc = y_test_proc.astype(int)
        except ValueError:
            print("Erro: Não foi possível converter y_test para numérico automaticamente.")
    # ---------------------------------------

    print("\nRelatório de Classificação (Teste):")
    # Agora passamos y_test_proc que é garantidamente numérico
    print(classification_report(y_test_proc, y_pred, target_names=['baixo', 'medio', 'alto']))
    
    print("\nMatriz de Confusão:")
    cm = confusion_matrix(y_test_proc, y_pred)
    
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=['baixo', 'medio', 'alto'], 
                yticklabels=['baixo', 'medio', 'alto'])
    plt.title(f'Matriz de Confusão - {name}')
    plt.ylabel('Real')
    plt.xlabel('Predito')
    plt.show()

In [ ]:


# Treinar e Avaliar LR Hierárquico
print("Treinando Modelos Finais LR...")
lr_s1 = LogisticRegression(max_iter=1000, random_state=42, **study_lr_s1.best_params)
pipe_lr_s1 = Pipeline(steps=[('preprocessor', preprocessor_lr), ('classifier', lr_s1)])
pipe_lr_s1.fit(X_train, y_train_s1)

lr_s2 = LogisticRegression(max_iter=1000, random_state=42, **study_lr_s2.best_params)
pipe_lr_s2 = Pipeline(steps=[('preprocessor', preprocessor_lr), ('classifier', lr_s2)])
pipe_lr_s2.fit(X_train_s2, y_train_s2)

evaluate_hierarchical(pipe_lr_s1, pipe_lr_s2, X_test, y_test, "Logistic Regression Hierárquica")

Treinando Modelos Finais LR...
--- Avaliação Hierárquica: Logistic Regression Hierárquica ---

ValueError: X has 180 features, but LogisticRegression is expecting 181 features as input.

In [115]:

# Treinar e Avaliar LGBM Hierárquico
print("Treinando Modelos Finais LGBM...")
lgbm_s1 = lgb.LGBMClassifier(objective='binary', metric='binary_logloss', verbosity=-1, boosting_type='gbdt', random_state=42, **study_lgbm_s1.best_params)
pipe_lgbm_s1 = Pipeline(steps=[('preprocessor', preprocessor_lgbm), ('classifier', lgbm_s1)])
pipe_lgbm_s1.fit(X_train, y_train_s1)

lgbm_s2 = lgb.LGBMClassifier(objective='binary', metric='binary_logloss', verbosity=-1, boosting_type='gbdt', random_state=42, **study_lgbm_s2.best_params)
pipe_lgbm_s2 = Pipeline(steps=[('preprocessor', preprocessor_lgbm), ('classifier', lgbm_s2)])
pipe_lgbm_s2.fit(X_train_s2, y_train_s2)

Treinando Modelos Finais LGBM...

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['km', 'latitude',
                                                   'longitude', 'mes',
                                                   'dia_semana_num']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('target_enc',
                                                                   TargetEncoder())]),
                                                  ['uf', 'br', 'fase_dia',
                                                   'sentido_via',
                                                   'condicao_metereologica',
                                                   'tipo_pista', 'tracado_via',
                                                   'uso_solo'])])),
                ('classifier',
                 LGBMClassifier(class_weight='balanced',
                                learning_rate=0.04061886830698239, max_depth=10,
                                metric='binary_logloss', n_estimators=412,
                                num_leaves=170, objective='binary',
                                random_state=42, verbosity=-1))])